# Generated by Django 4.2.13 on 2024-06-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Artista',
        ),
    ]
